services:
  db:
    image: mysql:9.1.0
    #command: mysqld --default_authentication_plugin=mysql_native_password #não se existe mais
    restart: always
    environment:
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: minha_senha  #A senha deve ser igual ao do banco, senão da erro de conexão jdbc
        MYSQL_USER: docker
        MYSQL_PASSWORD: minha_senha
        MYSQL_DATABASE: projeto_spring
    ports:
      - "3308:3306"
    expose:       #força uma porta a estar exposta
      - 3306
    networks:
      - projeto-network
  api-spring:                 #Minha API
    image: xthx/projeto-spring-boot
    restart: always
    build: . #Diz para que seja buildado por esse diretorio -> gera a docker image | "." representa o local desse arquivo (ex. ./Projeto Spring Boot)
    #working_dir: 'D:\Documentos\Java\Projeto Spring Boot'
    command: mvn spring-boot:run
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/projeto_spring?useTimezone=true&serverTimezone=UTC #Não esqueça de trocar localhost por db (container do sql)
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 47190Tulio
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - projeto-network
networks:
  projeto-network:
    driver: bridge