cors: #Config global do CORS - Propriedade manufaturada
  originPatterns: http://localhost:8080, http://localhost:3000
spring:
  application:
    name : demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: 47190Tulio
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: #org.hibernate.dialect.MySQLDialect - já adiciona sozinho quando vazio
    show-sql: false
    open-in-view: false
  logging:
      level:
        root: WARN #- Somente exibe logs de warn em pacotes root
        br.tulio.projetospring: DEBUG #Exibe todos os logs dos pacotes de br.tulio.projetospring
  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true