cors: #Config global do CORS - Propriedade manufaturada
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /Documentos/Java/FileDestination
email:
  subject: "Default Subject"
  message: "Default Message"
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000 # 1 hora
spring:
  application:
    name : demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: 47190Tulio
  jpa:
    hibernate:
      ddl-auto: none #Não usar o 'update' em produção
    properties:
      hibernate:
        dialect: #org.hibernate.dialect.MySQLDialect - já adiciona sozinho quando vazio
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  servlet:
    multipart:  #transferencia de Arquivos
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  logging:
      level:
        root: WARN #- Somente exibe logs de warn em pacotes root
        br.tulio.projetospring: DEBUG #Exibe todos os logs dos pacotes de br.tulio.projetospring
  spring-doc:
    paths-to-match:
      - /people/**
      - /auth/**
      - /file/**
      - /email/**
    swagger-ui:
      use-root-path: true